POST http://localhost:3000/register
content-type: application/json

{
    "email": "youremail@nafnes.com",
    "password": "123456"
}

### 

POST http://localhost:3000/login
content-type: application/json

{
    "email": "youremail@nafnes.com",
    "password": "123456"
}

###

GET  http://localhost:3000/example
content-type: application/json
authorization: Bearer [token]

###

POST  http://localhost:3000/example
content-type: application/json
authorization: Bearer [token]
{
  "firstName" : "Nafanesia",
  "lastName" : "Indonesia"
}